/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.ButtonGroup;
import Models.Clothing;
import Models.DBManager;
import Models.Footwear;
import Models.Staff;

/**
 *
 * @author 30240931 James Rourke
 */
public class AddProduct extends javax.swing.JFrame {
    //declare global ButtonGroup and loggedInStaff
    private ButtonGroup bg;
    private Staff loggedInStaff;

    /**
     * Creates new form AddProduct
     */
    public AddProduct(Staff staff) {
        initComponents();
        
        //set global loggedInStaff
        loggedInStaff = staff;
        
        //create instance of global ButtonGroup
        bg = new ButtonGroup();
       
        //Add clothing/footwear radio buttons to buttongroup
        bg.add(rdnClothing);
        bg.add(rdnFootwear);
        
        //hide extra attribute label and text box
        lblExtraAttribute.setVisible(false);
        txtExtraAttribute.setVisible(false);
        
      
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdnClothing = new javax.swing.JRadioButton();
        rdnFootwear = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtStockLevel = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblExtraAttribute = new javax.swing.JLabel();
        txtExtraAttribute = new javax.swing.JTextField();
        lblMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Add Product");

        jLabel2.setText("Type of Product:");

        rdnClothing.setText("Clothing");
        rdnClothing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnClothingActionPerformed(evt);
            }
        });

        rdnFootwear.setText("Footwear");
        rdnFootwear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnFootwearActionPerformed(evt);
            }
        });

        jLabel3.setText("Name:");

        jLabel4.setText("Price:");

        jLabel5.setText("Stock Level:");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnBack.setText("Return to Product Select");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblExtraAttribute.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(lblExtraAttribute))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdnClothing)
                                        .addGap(28, 28, 28)
                                        .addComponent(rdnFootwear))
                                    .addComponent(txtName)
                                    .addComponent(txtPrice)
                                    .addComponent(txtStockLevel)
                                    .addComponent(txtExtraAttribute))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClear)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdnClothing)
                    .addComponent(rdnFootwear))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtStockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExtraAttribute)
                    .addComponent(txtExtraAttribute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnClear)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdnClothingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnClothingActionPerformed
        //show hidden attribute and text
        lblExtraAttribute.setText("Measurement:");
        lblExtraAttribute.setVisible(true);
        txtExtraAttribute.setVisible(true);
    }//GEN-LAST:event_rdnClothingActionPerformed

    private void rdnFootwearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnFootwearActionPerformed
        //show hidden attribute and text
        lblExtraAttribute.setText("Size:");
        lblExtraAttribute.setVisible(true);
        txtExtraAttribute.setVisible(true);
    }//GEN-LAST:event_rdnFootwearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //go to modify products page
        ModifyProducts modifyProducts = new ModifyProducts(loggedInStaff);
        this.dispose();
        modifyProducts.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        //clear text boxes
        txtName.setText("");
        txtPrice.setText("");
        txtStockLevel.setText("");
        txtExtraAttribute.setText("");
        lblMessage.setText("");
        
        //clear button group
        bg.clearSelection();
        
        //hide attributes
        lblExtraAttribute.setVisible(false);
        txtExtraAttribute.setVisible(false);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        //get product details from view
        String productName = txtName.getText();
        String price = txtPrice.getText();
        String  stockLevel = txtStockLevel.getText();
        String extraAttribute = txtExtraAttribute.getText();
        
        //initialize integer/double variables
        int intStockLevel = 0;
        double doublePrice = 0;
        int intSize = 0;
        
       
       
        //check if clothing or footwear radio button is NOT selected
        if (!rdnClothing.isSelected() && !rdnFootwear.isSelected()) 
        {
            //Display error message
            lblMessage.setText("Error: Please select the type of Product you wish to add");
        }
        else
        {
        
        
        try
        {
           //parse string stockLevel to integer
           intStockLevel = Integer.parseInt(stockLevel); 
           try
           {
              //parse string price to double 
              doublePrice = Double.parseDouble(price);
              
              //check if clothing radio button is selected
               if (rdnClothing.isSelected()) 
               {
                   
                       //create new clothing object using details from user
                       Clothing clothing = new Clothing(productName, doublePrice, intStockLevel, extraAttribute);                       
                       DBManager db = new DBManager();  //declare instance of DBManager
                       db.addProduct(clothing); //call addProduct method and pass in the new product object
                       lblMessage.setText("Product Added Successfully");    //display success message
                       
                             
               }
               //if footwear radio button is selected
               else
               {
                   try
                   {
                       //parse string size to integer
                        intSize = Integer.parseInt(extraAttribute);   
                   }
                   //if parsing string size to integer fails
                   catch (Exception ex)
                   {
                       //display error message
                       lblMessage.setText("Error: Please enter integer value for size");
                   }
                   
                   //create new product using details from user
                   Footwear footwear = new Footwear(productName, doublePrice, intStockLevel, intSize);                   
                   DBManager db = new DBManager();  //create new instance of DBManager
                   db.addProduct(footwear); //call addProduct method and paas in new product
                   lblMessage.setText("Product Added Successfully");    //display success message
               }
           }
           //if parsing string price to decimal fails
           catch (Exception ex)
           {
               //display error message
              lblMessage.setText("Error: Please enter a decimal value for price");  
              String message = ex.getMessage();              
           }
        }
        //if parsing string stockLevel to integer fails
        catch(Exception ex)
        {
            //display error message
            lblMessage.setText("Error: Please enter an integer value for stock level"); 
            String message = ex.getMessage();
        }
       }
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblExtraAttribute;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JRadioButton rdnClothing;
    private javax.swing.JRadioButton rdnFootwear;
    private javax.swing.JTextField txtExtraAttribute;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtStockLevel;
    // End of variables declaration//GEN-END:variables
}
