/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.ButtonGroup;
import Models.Clothing;
import Models.DBManager;
import Models.Footwear;
import Models.Product;
import Models.Staff;

/**
 *
 * @author 30240931 James Rourke
 */
public class EditProduct extends javax.swing.JFrame {
    //Private Variables
    private Staff loggedInStaff;
    private Product product;

    /**
     * Creates new form AddProduct
     */
    public EditProduct(Staff staff, Product productIn) {
        initComponents();
        
        loggedInStaff = staff;
        product = productIn;
       
        txtID.setText(String.valueOf(product.getProductId()));
        txtName.setText(product.getProductName());
        txtPrice.setText(String.valueOf(product.getPrice()));
        txtStockLevel.setText(String.valueOf(product.getStockLevel()));
        
        if (product.getClass().getName().equals("Models.Clothing")) 
        {
            lblExtraAttribute.setText("Measurement: ");
            Clothing clothing = (Clothing)product;
            txtExtraAttribute.setText(clothing.getMeasurement());
        }
        else
        {
            lblExtraAttribute.setText("Size: ");
            Footwear footwear = (Footwear)product;
            txtExtraAttribute.setText(String.valueOf(footwear.getSize()));
        }
        
        txtID.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtStockLevel = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblExtraAttribute = new javax.swing.JLabel();
        txtExtraAttribute = new javax.swing.JTextField();
        lblMessage = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Edit Product");

        jLabel2.setText("ID:");

        jLabel3.setText("Name:");

        jLabel4.setText("Price:");

        jLabel5.setText("Stock Level:");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnUndo.setText("Undo");
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });

        btnBack.setText("Return to Product Select");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblExtraAttribute.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(lblExtraAttribute))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(txtPrice)
                                    .addComponent(txtStockLevel)
                                    .addComponent(txtExtraAttribute)
                                    .addComponent(txtID))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUndo)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtStockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExtraAttribute)
                    .addComponent(txtExtraAttribute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnUndo)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //go to modify products page
        ModifyProducts modifyProducts = new ModifyProducts(loggedInStaff);
        this.dispose();
        modifyProducts.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        txtID.setText(String.valueOf(product.getProductId()));
        txtName.setText(product.getProductName());
        txtPrice.setText(String.valueOf(product.getPrice()));
        txtStockLevel.setText(String.valueOf(product.getStockLevel()));
        lblMessage.setText("Undo Changes");
        if (product.getClass().getName().equals("Models.Clothing")) 
        {
            lblExtraAttribute.setText("Measurement: ");
            Clothing clothing = (Clothing)product;
            txtExtraAttribute.setText(clothing.getMeasurement());
        }
        else
        {
            lblExtraAttribute.setText("Size: ");
            Footwear footwear = (Footwear)product;
            txtExtraAttribute.setText(String.valueOf(footwear.getSize()));
        }
        
    }//GEN-LAST:event_btnUndoActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String productName = txtName.getText();
        String price = txtPrice.getText();
        String  stockLevel = txtStockLevel.getText();
        String extraAttribute = txtExtraAttribute.getText();
        
        int intStockLevel = 0;
        double doublePrice = 0;
        int intSize = 0;
        
        //Checks to see if nothing has been entered
        if (productName.equals("") || price.equals("") || stockLevel.equals("") || extraAttribute.equals("")) 
        {
            lblMessage.setText("Error: Please complete all fields");
        }

        try
        {
           intStockLevel = Integer.parseInt(stockLevel); 
           try
           {
               
              doublePrice = Double.parseDouble(price);
              
               if (product.getClass().getName().equals("Models.Clothing")) 
               {
//                     //String productNameIn, double priceIn, int stockLevelIn, int sizeIn
                       Clothing clothing = new Clothing(productName, doublePrice, intStockLevel, extraAttribute);  
                       clothing.setProductId(product.getProductId());
                       DBManager db = new DBManager();
                       db.editProduct(clothing);
                       lblMessage.setText("Product Updated Successfully");
                       product = clothing;
                           
               }
               else
               {
                   
                   try
                   {
                       intSize = Integer.parseInt(extraAttribute);
                   }
                   catch(Exception ex)
                   {
                       lblMessage.setText("Error: Please enter integer value for size");
                       String message = ex.getMessage();
                   }
                   //String productNameIn, double priceIn, int stockLevelIn, int sizeIn
                   Footwear footwear = new Footwear(productName, doublePrice, intStockLevel, intSize); 
                   footwear.setProductId(product.getProductId());
                   DBManager db = new DBManager();
                   db.editProduct(footwear);
                   lblMessage.setText("Product Updated Successfully");
                   product = footwear;
               }
           }
           catch (Exception ex)
           {
              lblMessage.setText("Error: Please enter a decimal value for price");  
              String message = ex.getMessage();              
           }
        }
        catch(Exception ex)
        {
            lblMessage.setText("Error: Please enter an integer value for stock level"); 
            String message = ex.getMessage();
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new EditProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUndo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblExtraAttribute;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTextField txtExtraAttribute;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtStockLevel;
    // End of variables declaration//GEN-END:variables
}
