/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Customer;
import Models.Staff;
import Models.User;
import Models.Order;
import Models.OrderLine;
import Models.Product;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 30240931 James Rourke
 */
public class PreviousOrderLines extends javax.swing.JFrame {

    /**
     * Creates new form PreviousOrderLines
     */
    private User loggedInUser;
    public PreviousOrderLines(User user, Customer customer,int orderId  ) {
        
        loggedInUser = user;
        initComponents();
        
        //Creates tej Table Model
        DefaultTableModel orderLines = (DefaultTableModel)tblOrderLines.getModel();
        
        Order order = customer.getOrders().get(orderId);
        
         //for each loop through HashMap
        for(Map.Entry<Integer, OrderLine> olEntry : order.getOrderLines().entrySet())
        {
            OrderLine actualOrderLine = olEntry.getValue();
            
            Product orderedProduct = new Product();
            
            String productId = "";
            String productName = "";
            int productQuantity = 0;
            String productCost = "";
            
            if(actualOrderLine.getProduct() == null) // Product has been deleted
            {
                productId = "N/A";
                productName = "N/A";
                productQuantity = 0;
                productCost = "N/A";
            }
            else
            {
                //reads the data from the Orderline
                orderedProduct = actualOrderLine.getProduct();
                productId = String.valueOf(orderedProduct.getProductId());
                productName = orderedProduct.toString();
                productQuantity = actualOrderLine.getQuantity();
                productCost = "£" + String.format("%.02f", orderedProduct.getPrice());
            }
            //Displays the data on the table
            orderLines.addRow(new Object[] 
                        {productId,
                        productName,
                        productQuantity,
                        productCost}                            
                );
        }
        
        tblOrderLines.setModel(orderLines);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderLines = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblOrderLines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductId", "Product", "Quantity", "Price"
            }
        ));
        jScrollPane1.setViewportView(tblOrderLines);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if(loggedInUser.getClass().getName().equals("Models.Staff"))
        {
            StaffPreviousOrders spv = new StaffPreviousOrders((Staff)loggedInUser);
            this.dispose();
            spv.setVisible(true);
        }
        else
        {
            CustomerPreviousOrders zkOrders = new CustomerPreviousOrders((Customer)loggedInUser);
            this.dispose();
            zkOrders.setVisible(true);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreviousOrderLines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreviousOrderLines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreviousOrderLines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreviousOrderLines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //  new PreviousOrderLines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrderLines;
    // End of variables declaration//GEN-END:variables
}
